### PR TITLE
Format docs

### PR DESCRIPTION
**Pull request by dalmasonto**
I just created a fork of your fork so as to see where things go wrong, just found out that some how when you run `npm run format` it sought of leaves these two files not formated according to the code style for the starknetbook documentation 
image
With this, you can merge to your main branch but just confirm whether things are right and your work is not lost

### CODE REVIEW

**Comment by devnet0x** [comment]
but those files are not mine, i dont know if they are ok afterprettier

**Comment by dalmasonto** [comment]
Yea, they will be okay, what prettier does is just to add missing spaces and formatting the source code accordingly, I talked with one of the contributors of the same files and they said they also didn't know about prettier before now they know about it. It does not delete any work done by somebody, just adding missing spaces, maybe lines

**Comment by dalmasonto** [comment]
Actually both of them, they had sent their work without formatting it because that step has not been captured in the main ReadMe. But I have create a PR for the same to add those steps so that each contributor can format their work before commiting.

**Comment by dalmasonto** [comment]
Actually if you look at the changes, you will notice that nothing really changed on them

**Comment by devnet0x** [comment]
now i include those file in commit...thanks😬

**Comment by dalmasonto** [comment]
Welcome

**Pull request merged**
